2022-06-08 12:12:16,275 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 12:12:16,275 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:20:06,163 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:20:06,163 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:21:49,384 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:21:49,384 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:35:58,292 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:35:58,292 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:37:21,444 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:37:21,444 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:37:25,581 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:37:25,596 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:37:27,140 DEBUG client_app.py Keys loaded
2022-06-08 17:41:33,174 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:41:33,174 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:41:37,817 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:41:37,831 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:41:37,999 DEBUG client_app.py Keys loaded
2022-06-08 17:49:40,224 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:49:40,224 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:49:44,649 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:49:44,678 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:49:44,836 DEBUG client_app.py Keys loaded
2022-06-08 17:50:28,896 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:50:28,896 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:50:32,893 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:50:32,906 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:50:33,066 DEBUG client_app.py Keys loaded
2022-06-08 17:53:44,253 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:53:44,253 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:53:48,813 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:53:48,823 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:54:13,110 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:54:13,111 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:54:17,385 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:54:17,398 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:54:17,564 DEBUG client_app.py Keys loaded
2022-06-08 17:55:08,973 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:55:08,973 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:55:15,617 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:55:15,632 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:55:15,778 DEBUG client_app.py Keys loaded
2022-06-08 17:56:03,107 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 17:56:03,107 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 17:56:06,802 DEBUG client_app.py Username = ara, password = 1
2022-06-08 17:56:06,817 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 17:56:06,969 DEBUG client_app.py Keys loaded
2022-06-08 21:16:42,407 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 21:16:42,407 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 21:16:52,385 DEBUG client_app.py Username = ara, password = 1
2022-06-08 21:16:52,401 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 21:16:52,544 DEBUG client_app.py Keys loaded
2022-06-08 21:28:40,218 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 21:28:40,218 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 21:28:44,134 DEBUG client_app.py Username = ara, password = 1
2022-06-08 21:28:44,151 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 21:28:44,313 DEBUG client_app.py Keys loaded
2022-06-08 21:36:38,115 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 21:36:38,116 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 21:36:43,295 DEBUG client_app.py Username = ara, password = 1
2022-06-08 21:36:43,324 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 21:36:59,411 DEBUG client_app.py Keys loaded
2022-06-08 22:41:48,278 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 22:41:48,279 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 22:41:53,237 DEBUG client_app.py Username = ara, password = 1
2022-06-08 22:41:53,258 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 22:41:53,656 DEBUG client_app.py Keys loaded
2022-06-08 22:44:59,544 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-08 22:44:59,544 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-08 22:45:03,364 DEBUG client_app.py Username = ara, password = 1
2022-06-08 22:45:03,379 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-08 22:45:10,269 DEBUG client_app.py Keys loaded
2022-06-11 12:58:22,439 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-11 12:58:22,445 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-11 12:58:31,488 DEBUG client_app.py Username = ara, password = 1
2022-06-11 12:58:31,513 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-11 12:58:31,685 DEBUG client_app.py Keys loaded
2022-06-11 16:01:28,803 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-11 16:01:28,809 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-11 16:01:36,086 DEBUG client_app.py Username = ara, password = 1
2022-06-11 16:01:36,110 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-11 16:01:36,270 DEBUG client_app.py Keys loaded
2022-06-11 17:35:40,802 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-11 17:35:40,802 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-11 17:35:45,646 DEBUG client_app.py Username = ara, password = 1
2022-06-11 17:35:45,670 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-11 17:35:45,828 DEBUG client_app.py Keys loaded
2022-06-11 17:40:25,728 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-11 17:40:25,728 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-11 17:40:28,992 DEBUG client_app.py Username = ara, password = 1
2022-06-11 17:40:29,008 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-11 17:40:29,181 DEBUG client_app.py Keys loaded
2022-06-11 17:41:26,903 DEBUG decos.py вызвана функция arg_parser с параметрами (), {}.Вызов из модуля __main__.
2022-06-11 17:41:26,903 DEBUG client_app.py Аргументы получены. Клиент None запустился с параметрами 127.0.0.1: 8888
2022-06-11 17:41:30,592 DEBUG client_app.py Username = ara, password = 1
2022-06-11 17:41:30,604 INFO client_app.py Запущен клиент с параметрами 127.0.0.1 : 8888, имя пользователя: ara
2022-06-11 17:41:34,134 DEBUG client_app.py Keys loaded
2022-06-11 18:10:51,622 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:10:51,643 DEBUG client_app.py Args loaded
2022-06-11 18:10:55,525 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:10:55,525 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:10:55,622 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:10:55,654 INFO transport.py Попытка подключения №1
2022-06-11 18:10:58,693 INFO transport.py Попытка подключения №2
2022-06-11 18:11:01,733 INFO transport.py Попытка подключения №3
2022-06-11 18:11:04,771 INFO transport.py Попытка подключения №4
2022-06-11 18:11:07,822 INFO transport.py Попытка подключения №5
2022-06-11 18:11:10,856 CRITICAL transport.py Не удалось установить соединение с сервером
2022-06-11 18:38:31,017 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:38:31,048 DEBUG client_app.py Args loaded
2022-06-11 18:38:35,370 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:38:35,370 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:38:35,479 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:38:35,534 INFO transport.py Попытка подключения №1
2022-06-11 18:38:35,534 DEBUG transport.py Connection established.
2022-06-11 18:38:35,535 DEBUG transport.py Starting auth dialog.
2022-06-11 18:38:35,553 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 18:38:35,554 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654961915.5545487, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:38:35,554 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=508, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 51452), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654961915.5545487, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 18:38:35,555 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=508, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 51452), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 18:38:40,555 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 18:43:07,786 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:43:07,802 DEBUG client_app.py Args loaded
2022-06-11 18:43:11,526 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:43:11,527 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:43:11,603 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:43:11,651 INFO transport.py Попытка подключения №1
2022-06-11 18:43:11,652 DEBUG transport.py Connection established.
2022-06-11 18:43:11,653 DEBUG transport.py Starting auth dialog.
2022-06-11 18:43:11,667 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 18:43:11,667 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654962191.6673431, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:43:11,667 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 52188), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654962191.6673431, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 18:43:11,668 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 52188), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 18:43:16,669 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 18:44:46,362 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:44:46,378 DEBUG client_app.py Args loaded
2022-06-11 18:44:50,586 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:44:50,586 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:44:50,663 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:44:50,704 INFO transport.py Попытка подключения №1
2022-06-11 18:44:50,705 DEBUG transport.py Connection established.
2022-06-11 18:44:50,705 DEBUG transport.py Starting auth dialog.
2022-06-11 18:44:50,716 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 18:44:50,716 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654962290.7167668, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:44:50,716 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1280, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 62084), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654962290.7167668, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 18:44:50,717 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1280, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 62084), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 18:44:55,717 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 18:45:05,303 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:45:05,318 DEBUG client_app.py Args loaded
2022-06-11 18:45:08,810 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:45:08,810 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:45:08,981 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:45:09,046 INFO transport.py Попытка подключения №1
2022-06-11 18:45:09,047 DEBUG transport.py Connection established.
2022-06-11 18:45:09,047 DEBUG transport.py Starting auth dialog.
2022-06-11 18:45:09,057 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 18:45:09,058 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654962309.0581274, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:45:09,058 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63701), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654962309.0581274, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 18:45:09,059 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63701), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 18:45:14,059 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 18:45:34,151 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 18:45:34,167 DEBUG client_app.py Args loaded
2022-06-11 18:45:37,802 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 18:45:37,802 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 18:45:37,874 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 18:45:37,916 INFO transport.py Попытка подключения №1
2022-06-11 18:45:37,917 DEBUG transport.py Connection established.
2022-06-11 18:45:37,917 DEBUG transport.py Starting auth dialog.
2022-06-11 18:45:37,928 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 18:45:37,928 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654962337.9283338, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 18:45:37,928 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1028, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63702), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654962337.9283338, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 18:45:37,928 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1028, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63702), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 18:45:42,929 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 20:04:15,803 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 20:04:15,819 DEBUG client_app.py Args loaded
2022-06-11 20:04:19,298 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 20:04:19,298 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 20:04:19,370 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 20:04:19,413 INFO transport.py Попытка подключения №1
2022-06-11 20:04:19,413 DEBUG transport.py Connection established.
2022-06-11 20:04:19,414 DEBUG transport.py Starting auth dialog.
2022-06-11 20:04:19,425 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 20:04:19,425 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654967059.4250512, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 20:04:19,425 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 52883), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654967059.4250512, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 20:04:19,426 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 52883), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 20:04:24,426 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 20:04:58,258 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 20:04:58,289 DEBUG client_app.py Args loaded
2022-06-11 20:05:02,067 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 20:05:02,067 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 20:05:02,147 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 20:05:02,187 INFO transport.py Попытка подключения №1
2022-06-11 20:05:02,188 DEBUG transport.py Connection established.
2022-06-11 20:05:02,188 DEBUG transport.py Starting auth dialog.
2022-06-11 20:05:02,197 DEBUG transport.py Passwd hash ready: b'0811ee1b33ba82a511d6d2449c6e3d7ee1c19bf3ae571463a0aa69d2fb59d64128bddf93b804ddb6e9acfb51631ce1989358c5825059bdfb567bd0aaaa7d11c1'
2022-06-11 20:05:02,198 DEBUG transport.py Presense message = {'action': 'presence', 'time': 1654967102.1986547, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-06-11 20:05:02,198 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1092, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 53000), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1654967102.1986547, 'user': {'account_name': 'ara', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzj9cOArvtS2pHTetllCn\n8uB5P/WpSoWSY5oc4x0or2/FXFY03H4acEootiyAq+xbZ31N08IXy/H1C9tlj+Ie\nwGuqZ1dpN41vKadVzaLkNXUSvC4OnsbciW/YAux/pztT4leWK9v/n3q+qR4VWQTf\nf2CJzHSov7oAxnLuvgJo1cHuWgmEo0F2NITTy9Ax/PxveM0HVjCiRATR0Ucg6FaV\n8GqmCO6pnYuQrlzwmTDdg8men6I8AF9tRrizvjZA0AUCgEu4MBLtDUZ4xnK/13X9\nOnf1wjx6AvsjXAboloALcVeL9Q6oL16YuzUQAP5nGxZycWyS7koCSzOG0QYROcFs\nbwIDAQAB\n-----END PUBLIC KEY-----'}}) , {}. Вызов из модуля common.utils
2022-06-11 20:05:02,198 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1092, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 53000), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2022-06-11 20:05:07,198 DEBUG transport.py Connection error.
Traceback (most recent call last):
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\client\transport.py", line 121, in connection_init
    ans = get_message(self.transport)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\decos.py", line 28, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\эльдо\PycharmProjects\db_PyQT\app\common\utils.py", line 15, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
socket.timeout: timed out
2022-06-11 20:05:35,345 DEBUG decos.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2022-06-11 20:05:35,345 DEBUG client_app.py Args loaded
2022-06-11 20:05:39,899 DEBUG client_app.py Using USERNAME = ara, PASSWD = 1.
2022-06-11 20:05:39,899 INFO client_app.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ara
2022-06-11 20:05:40,060 DEBUG client_app.py Keys sucsessfully loaded.
2022-06-11 20:05:40,125 INFO transport.py Попытка подключения №1
2022-06-11 20:05:43,174 INFO transport.py Попытка подключения №2
2022-06-11 20:05:46,198 INFO transport.py Попытка подключения №3
2022-06-11 20:05:49,214 INFO transport.py Попытка подключения №4
2022-06-11 20:05:52,248 INFO transport.py Попытка подключения №5
2022-06-11 20:05:55,270 CRITICAL transport.py Не удалось установить соединение с сервером
